name: Update Homebrew Formula with Latest CLI Version and Checksums

#on:
#  workflow_dispatch:
on:
  push:
    branches:
      - test-branch


jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Homebrew Tap Repository
        uses: actions/checkout@v2
        with:
          repository: 'streamdal/homebrew-tap'
          path: 'homebrew-tap'
      
      - name: Setup jq and curl
        run: sudo apt-get update && sudo apt-get install jq curl

      - name: Fetch Latest CLI Release Version and Asset URLs
        id: fetch_info
        run: |
          LATEST_RELEASE=$(gh api repos/streamdal/streamdal/releases | jq -r '.[] | select(.tag_name | startswith("apps/cli")) | .tag_name' | head -1)
          echo "LATEST_RELEASE=$LATEST_RELEASE" >> $GITHUB_ENV
          # Extracting URLs and names for all assets
          ASSETS=$(gh api repos/streamdal/streamdal/releases | jq -r --arg LATEST_RELEASE "$LATEST_RELEASE" '.[] | select(.tag_name == $LATEST_RELEASE) | .assets[] | {name, browser_download_url} | @base64')
          echo "::set-output name=assets::$ASSETS"
        env:
           GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Update cli.rb with the Latest URLs and sha256 Checksums
        run: |
          # Define the expected asset names according to your naming convention
          declare -A ASSET_NAMES=(
            ["darwin-arm64"]="streamdal-darwin-arm64"
            ["darwin-amd64"]="streamdal-darwin"
            ["linux-amd64"]="streamdal-linux"
          )

          # Update the version in cli.rb
          sed -i "s|apps%2Fcli%2Fv[0-9.]*|apps%2Fcli%2Fv${LATEST_RELEASE#apps/cli/}|g" homebrew-tap/cli.rb

          for ARCH in "${!ASSET_NAMES[@]}"; do
            ASSET_NAME=${ASSET_NAMES[$ARCH]}
            # Fetch the asset URL using GitHub CLI and jq
            ASSET_URL=$(gh api repos/streamdal/streamdal/releases | jq -r --arg ASSET_NAME "$ASSET_NAME" --arg LATEST_RELEASE "$LATEST_RELEASE" '.[] | select(.tag_name == $LATEST_RELEASE) | .assets[] | select(.name == $ASSET_NAME) | .browser_download_url')
            # Download the asset and calculate its sha256
            SHA256=$(curl -Ls $ASSET_URL | shasum -a 256 | awk '{print $1}')

            # Update URL and sha256 for each platform in cli.rb
            sed -i "s|url \".*\/$ASSET_NAME\"|url \"$ASSET_URL\"|g" homebrew-tap/cli.rb
            sed -i "s|sha256 \".*\" # $ARCH|sha256 \"$SHA256\" # $ARCH|g" homebrew-tap/cli.rb

            echo "Updated $ARCH to $LATEST_RELEASE with sha256 $SHA256"
          done

      - name: Commit and Push Changes
        run: |
          cd homebrew-tap
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git add cli.rb
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update CLI formula to $LATEST_RELEASE"
            git push
          fi
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

name: Update Homebrew Formula

on:
  workflow_dispatch:

jobs:
  update-homebrew-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Homebrew Tap Repository
        uses: actions/checkout@v2
        with:
          repository: 'streamdal/homebrew-tap'
          path: 'homebrew-tap'

      - name: Setup jq and curl
        run: sudo apt-get update && sudo apt-get install jq curl

      - name: Fetch Latest CLI Release Version
        id: latest_version
        run: |
          LATEST_VERSION=$(gh api repos/streamdal/streamdal/releases | jq -r '.[] | select(.tag_name | startswith("apps/cli")) | .tag_name' | head -1 | cut -d '/' -f 3)
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
        env:
           GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Fetch Asset Download URLs and Names
        id: asset_info
        run: |
          ASSET_JSON=$(gh api repos/streamdal/streamdal/releases/tags/apps/cli/$LATEST_VERSION | jq -r '.assets[] | {name, browser_download_url}')
          echo "ASSET_JSON=$ASSET_JSON" >> $GITHUB_ENV
        env:
           GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Update cli.rb with the New Download URLs and Checksums
        run: |
          for asset in $(echo $ASSET_JSON | jq -r '.name'); do
            DOWNLOAD_URL=$(echo $ASSET_JSON | jq -r --arg name "$asset" '. | select(.name==$name) | .browser_download_url')
            SHA256=$(curl -Ls $DOWNLOAD_URL | shasum -a 256 | awk '{print $1}')
            
            # Update URL and sha256 in cli.rb
            sed -i "s|url \".*${asset}\"|url \"$DOWNLOAD_URL\"|g" homebrew-tap/cli.rb
            sed -i "s|sha256 \".*\" # ${asset}|sha256 \"$SHA256\" # ${asset}|g" homebrew-tap/cli.rb
            
            echo "Updated asset $asset with sha256 $SHA256"
          done

      - name: Commit and Push Changes
        run: |
          cd homebrew-tap
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git add cli.rb
          git commit -m "Update CLI formula to version $LATEST_VERSION"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
