name: Update Homebrew Formula with Latest CLI Version and Checksums

#on:
#  workflow_dispatch:
on:
  push:
    branches:
      - test-branch

jobs:
  update-homebrew-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Homebrew Tap Repository
        uses: actions/checkout@v2
        with:
          repository: 'streamdal/homebrew-tap'
          path: 'homebrew-tap'

      - name: Setup jq and curl
        run: sudo apt-get update && sudo apt-get install jq curl

      - name: Fetch Latest CLI Release Version
        id: latest_release
        run: |
          LATEST_RELEASE=$(gh api repos/streamdal/streamdal/releases | jq -r '.[] | select(.tag_name | startswith("apps/cli")) | .tag_name' | head -1 | cut -d '/' -f 3)
          echo "LATEST_RELEASE=$LATEST_RELEASE" >> $GITHUB_ENV
        env:
           GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Fetch Asset Download URLs and Names
        id: asset_info
        run: |
          ASSET_JSON=$(gh api repos/streamdal/streamdal/releases | jq -r --arg LATEST_RELEASE "$LATEST_RELEASE" '.[] | select(.tag_name == $LATEST_RELEASE) | .assets[] | {name, browser_download_url}')
          echo "ASSET_JSON=$ASSET_JSON" >> $GITHUB_ENV
        env:
           GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Update cli.rb with the New Download URLs and Checksums
        run: |
          for asset in $(echo $ASSET_JSON | jq -r '.name'); do
            DOWNLOAD_URL=$(echo $ASSET_JSON | jq -r --arg name "$asset" '. | select(.name==$name) | .browser_download_url')
            SHA256=$(curl -Ls $DOWNLOAD_URL | shasum -a 256 | awk '{print $1}')
            
            # Update URL and sha256 in cli.rb
            sed -i "s|url \".*${asset}\"|url \"$DOWNLOAD_URL\"|g" homebrew-tap/cli.rb
            sed -i "s|sha256 \".*\" # ${asset}|sha256 \"$SHA256\" # ${asset}|g" homebrew-tap/cli.rb
            
            echo "Updated asset $asset with sha256 $SHA256"
          done

      - name: Commit and Push Changes
        run: |
          cd homebrew-tap
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git add cli.rb
          git commit -m "Update CLI formula to version $LATEST_RELEASE"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
